name: panoptes-tutorials

channels:
  - astropy
  - conda-forge

dependencies:
  - pip
  - python>=3.7
  - jupyterlab
  - ipywidgets
  - altair
  - numpy
  - matplotlib
  - pandas
  - dask
  - scikit-image
  - scikit-learn
  - seaborn
  - pymongo
  - pip:
    - astroplan
    - jupyter-offlinenotebook
    - panoptes-utils
    - -e git+git://github.com/panoptes/POCS@docker#egg=pocs
    
