name: panoptes-tutorials

channels:
  - astropy


dependencies:
  - python>=3.7
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - ctypes
  - pip:
    - astroplan
    - -e git+git://github.com/panoptes/POCS@develop#egg=pocs
    - -e git+git://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils
